version: '3.7'

services:
  mongo:
    image: mongo:4.2.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
    - '27017:27017'
    restart: always

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    ports:
    - '8081:8081'
    restart: always
