version: '3.7'

services:
  rethinkdb:
    build:
      context: .
    ports:
    - '8080:8080'
    - '28015:28015'
    volumes:
    - ../config/:/tls/:ro
    - rethinkdb:/data/

volumes:
  rethinkdb:
