root: true
env:
  browser: true
  es2021: true
extends:
- 'eslint:recommended'
- 'airbnb-typescript/base'
- 'plugin:@typescript-eslint/recommended'
- 'plugin:vue/vue3-recommended'
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  project: './tsconfig.json'
  sourceType: 'module'
  extraFileExtensions: [ '.vue' ]
plugins:
- '@typescript-eslint'
rules: { }
ignorePatterns:
- '*.*'
- '!*.ts'
- '!*.vue'
- 'dist/'
