POST https://localhost:8080/suites
Content-Type: application/json

{
  "failure_types": [
    {
      "name": "Selenium Error",
      "description": "Something went wrong here!"
    }
  ],
  "tags": [
    "smoke",
    "gy"
  ],
  "env_vars": [
    {
      "key": "BROWSER",
      "value": "CHROME"
    }
  ],
  "attachments": [
    "1234567890"
  ],
  "planned_cases": 3,
  "created_at": 0
}

###

POST https://localhost:8080/suites/5ea645714f34fbb33044c83b/cases
Content-Type: application/json

{
  "name": "GY checkout",
  "num": 1,
  "links": [
    {
      "type": "other",
      "name": "JIRA",
      "url": "https://jira.derp.com/"
    }
  ],
  "description": "A new feature test",
  "started_at": 1587256716
}

###

POST https://localhost:8080/cases/5ea7875d530c0d5a96437af8/logs
Content-Type: application/json

{
  "level": "info",
  "message": "Hello, world!",
  "timestamp": 1587256716
}

###

PATCH https://localhost:8080/suites/5ea63dba1bb2e1ee2a66dc6d
Content-Type: application/json

{
  "status": "finished",
  "finished_at": 1587256710
}