version: '3.7'

services:
  mongo:
    build:
      context: .
    ports:
    - '27017:27017'
    restart: always

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports:
    - '8081:8081'
    restart: always
    depends_on:
    - mongo
