version: '3.8'

services:
  mongo:
    build: .
    environment:
      MONGO_INITDB_DATABASE: admin
    ports:
    - 27017:27017
  mongo-express:
    image: mongo-express:0.54
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_SITE_SSL_ENABLED: 'true'
      ME_CONFIG_SITE_SSL_CRT_PATH: /tls/cert.pem
      ME_CONFIG_SITE_SSL_KEY_PATH: /tls/key.pem
      ME_CONFIG_OPTIONS_EDITORTHEME: darcula
    ports:
    - 8082:8081
    volumes:
    - ../tls:/tls:ro
